// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WishList;

namespace WishList.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("WishList.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductMetaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("timeRetreived")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductMetaId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WishList.ProductMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameHtmlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceHtmlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductMeta");
                });

            modelBuilder.Entity("WishList.Product", b =>
                {
                    b.HasOne("WishList.ProductMeta", null)
                        .WithMany("product")
                        .HasForeignKey("ProductMetaId");
                });
#pragma warning restore 612, 618
        }
    }
}
